angular.module('AgaveToGo').controller('AppEditWizardController', function ($injector, $timeout, $rootScope, $scope, $state, $location, $stateParams, $q, $uibModal, $localStorage, $location, Commons, AppsController, WizardHandler, SystemsController, SystemTypeEnum, Tags, FilesController) {

    $scope.schema = {
        "type": "object",
        "title": "Interactive app registration form for the Agave platform.",
        "properties": {
            "name": {
                "type": "string",
                "description": "The name of the application. The name does not have to be unique, but the combination of name and version does.",
                "title": "Name",
                "validator": "[a-zA-Z_\\-\\.]+",
                "minLength": 3,
                "maxLength": 64
            },
            "version": {
                "type": "string",
                "description": "The version of the application in #.#.# format. While the version does not need to be unique, the combination of name and version does have to be unique.",
                "title": "Version",
                "validator": "\\d+(\\.\\d+)+",
                "minLength": 3,
                "maxLength": 16
            },
            "helpURI": {
                "type": "string",
                "description": "The URL where users can go for more information about the app.",
                "format": "url",
                "title": "Help URL",
                "validator": "(http|https)://[\\w-]+(\\.[\\w-]*)+([\\w.,@?^=%&amp;:/~+#-]*[\\w@?^=%&amp;/~+#-])?"
            },
            "label": {
                "type": "string",
                "description": "Label for use in forms generated by the jobs service",
                "title": "Label"
            },
            "icon": {
                "type": "string",
                "description": "The icon url to associate with this app.",
                "title": "Icon",
                "validator": "(http|https)://[\\w-]+(\\.[\\w-]*)+([\\w.,@?^=%&amp;:/~+#-]*[\\w@?^=%&amp;/~+#-])?"
            },
            "shortDescription": {
                "type": "string",
                "description": "Short description of this app",
                "maxLength": 128,
                "title": "Short description"
            },
            "longDescription": {
                "type": "string",
                "description": "Full description of this app",
                "maxLength": 32768,
                "title": "Long description"
            },
            "defaultQueue": {
                "type": [null,"string"],
                "description": "Default queue to use when submitting this job if none is provided in the job request. Can be left blank and a queue will be determined at run time.",
                "maxLength": 128,
                "title": "Default queue"
            },
            "defaultNodeCount": {
                "type": "integer",
                "description": "Default number of nodes to be used when running this app if no node count is given in the job request",
                "maxLength": 12,
                "minimum": 0,
                "exclusiveMinimum": true,
                "title": "Default node count",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 1
                }
            },
            "defaultMemoryPerNode": {
                "type": "number",
                "description": "Default memory in GB to be used when running this app if no memory is given in the job request",
                "maxLength": 9,
                "minimum": 0,
                "exclusiveMinimum": true,
                "title": "Default memory (GB)",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 4
                }
            },
            "defaultProcessorsPerNode": {
                "type": "integer",
                "description": "Default number of processors per node to be used when running this app if no processor count is given in the job request",
                "maxLength": 12,
                "title": "Default processor count",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 1
                }
            },
            "defaultMaxRunTime": {
                "type": "string",
                "description": "Default max run time to be used when running this app if no requested run time is given in the job request",
                "maxLength": 10,
                "title": "Default run time",
                "validator": "^(?:[0-9]{1,3}?[0-9]):[0-5][0-9]:[0-5][0-9]$",
                "x-schema-form": {
                    "type": "input",
                    "placeholder": "24:00:00"
                }
            },
            "ontology": {
                "type": "array",
                "description": "An array of ontology terms describing this app.",
                "items": {
                    "type": "string"
                },
                "title": "Ontology"
            },
            "executionSystem": {
                "type": "string",
                "description": "The ID of the execution system where this app should run.",
                "items": [],
                "title": "Execution system"
            },
            "executionType": {
                "type": "string",
                "description": "The execution type of the application. If you're unsure, it's probably HPC.",
                "enum": [
                    "CLI", "HPC", "CONDOR"
                ],
                "title": "Execution type"
            },
            "parallelism": {
                "type": "string",
                "description": "The parallelism type of the application. If you're unsure, it's probably SERIAL.",
                "enum": [
                    "SERIAL",
                    "PARALLEL",
                    "PTHREAD"
                ],
                "title": "Parallelism"
            },
            "deploymentPath": {
                "type": "string",
                "description": "The path to the folder on the deployment system containing the application wrapper and dependencies.",
                "title": "Deployment path"
            },
            "deploymentSystem": {
                "type": "string",
                "description": "The ID of the storage system where this app's assets should be stored.",
                "items": [],
                "title": "Deployment system"
            },
            "templatePath": {
                "type": "string",
                "description": "The path to the wrapper script relative to the deploymentPath.",
                "title": "Wrapper script"
            },
            "testPath": {
                "type": "string",
                "description": "The path to the test script relative to the deploymentPath.",
                "title": "Test script"
            },
            "checkpointable": {
                "type": "boolean",
                "description": "Does this app support checkpointing?",
                "title": "Checkpointable"
            },
            "tags": {
                "type": "array",
                "description": "Array of terms you may associate with this app",
                "items": {
                    "type": "string"
                },
                "title": "Tags"
            },
            "modules": {
                "type": "array",
                "description": "An array of modules to load prior to the execution of the application. This is only relevant when you use the unix Modules or LMOD utilities to manage dependencies on the app execution system.",
                "items": {
                    "type": "string",
                },
                // "required": [],
                "title": "Modules"
            },
            //"inputs": {
            //    "type": "array",
            //    "items": {
            //        "type": "object",
            //        "properties": {
            //            "id": {
            //                "type": "string",
            //                "description": "The unique identifier for this input file. This will be referenced in the wrapper script.",
            //                "required": true,
            //                "title": "ID",
            //                "valueInLegend": true
            //            },
            //            "details": {
            //                "type": "object",
            //                "description": "Descriptive details about this app input file used in form generation.",
            //                "title": "Details",
            //                "properties": {
            //                    "label": {
            //                        "type": "string",
            //                        "description": "The label for this input.",
            //                        "title": "Label"
            //                    },
            //                    "description": {
            //                        "type": "string",
            //                        "description": "Description of this input.",
            //                        "title": "Description"
            //                    },
            //                    "argument": {
            //                        "type": "string",
            //                        "description": "The command line value of this input (ex -n, --name, -name, etc)",
            //                        "title": "Command line argument",
            //                        "default": ""
            //                    },
            //                    "showArgument": {
            //                        "type": "boolean",
            //                        "description": "Whether the argument value should be passed into the wrapper at run time?",
            //                        "title": "Add command line argument?",
            //                        "default": false
            //                    },
            //                    "repeatArgument": {
            //                        "type": "boolean",
            //                        "description": "Whether the argument value should be repeated in front of each user-supplied input before injection into the wrapper template at runtime?",
            //                        "title": "Add command line argument?",
            //                        "default": false
            //                    }
            //                }
            //            },
            //            "semantics": {
            //                "type": "object",
            //                "description": "Semantic information about the input field.",
            //                "title": "Semantics",
            //                "properties": {
            //                    "minCardinality": {
            //                        "type": "integer",
            //                        "description": "Minimum number of instances of this input per job.",
            //                        "title": "Min cardinality",
            //                        "default": 0,
            //                        "required": false
            //                    },
            //                    "maxCardinality": {
            //                        "title": "Max cardinality",
            //                        "type": "integer",
            //                        "description": "Max number of instances of this input per job.",
            //                        "default": -1,
            //                        "required": false
            //                    },
            //                    "ontology": {
            //                        "title": "Ontology",
            //                        "type": "array",
            //                        "description": "Array of ontology terms describing this app.",
            //                        "items": {
            //                            "type": "string"
            //                        }
            //                    },
            //                    "fileTypes": {
            //                        "type": "array",
            //                        "description": "Array of file types required for this input.",
            //                        "items": {
            //                            "type": "string"
            //                        },
            //                        "title": "File types"
            //                    }
            //                }
            //            },
            //            "value": {
            //                "type": "object",
            //                "description": "Default value and validations for the input field.",
            //                "title": "Value",
            //                "properties": {
            //                    "default": {
            //                        "type": "string",
            //                        "description": "The default value to use for this input.",
            //                        "title": "Default value"
            //                    },
            //                    "validator": {
            //                        "type": "string",
            //                        "description": "The regular expression used to validate this input value.",
            //                        "title": "Validator"
            //                    },
            //                    "required": {
            //                        "type": "boolean",
            //                        "description": "Is this input required? If visible is false, this must be true.",
            //                        "title": "Required",
            //                        "default": 1,
            //                        "required": true
            //                    },
            //                    "visible": {
            //                        "type": "boolean",
            //                        "description": "Should this parameter be visible? If not, there must be a default and it will be required..",
            //                        "title": "Visible",
            //                        "default": true,
            //                        "required": true
            //                    },
            //                    "order": {
            //                        "type": "integer",
            //                        "description": "The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which inputs are returned in the response json.",
            //                        "title": "Order",
            //                        "default": 0
            //                    },
            //                    "enquote": {
            //                        "type": "boolean",
            //                        "description": "Should this value be double quoted prior to injection in the wrapper template.",
            //                        "title": "Visible",
            //                        "default": true,
            //                        "required": true
            //                    }
            //                }
            //            }
            //        }
            //    }
            //},
            "parameters": {
                "type": "array",
                "description": "Non-file inputs supported by this application.",
                "items": {
                    "type": "object",
                    "title": "Parameter",
                    "properties": {
                        "id": {
                            "type": "string",
                            maxLength: 256,
                            minLength: 1,
                            "description": "The unique identifier for this parameter. This will be referenced in the wrapper script.",
                            "title": "Parameter ID"
                        },
                        "details": {
                            "type": "object",
                            "description": "Descriptive details about this app parameter used in form generation.",
                            "title": "Details",
                            "properties": {
                                "label": {
                                    "type": "string",
                                    "description": "The label displayed for this parameter .",
                                    "title": "Label"
                                },
                                "description": {
                                    "type": "string",
                                    "description": "Verbose information on what this parameter does.",
                                    "title": "Description"
                                },
                                "showArgument": {
                                    "type": "boolean",
                                    "description": "Should this command line argument be injected into the submit script preceding the parameter?",
                                    "title": "Prepend command line argument?"
                                },
                                "argument": {
                                    "type": "string",
                                    "description": "Name of the command line flag or argument (including dashes) for this parameter.",
                                    "title": "Argument value"
                                },
                                "repeatArgument": {
                                    "type": "boolean",
                                    "description": "In instances where multiple values are supplied for this parameter, should this command line argument be repeatedly injected into the submit script preceding every instance of the parameter value?",
                                    "title": "Repeat argument for every value?"
                                }
                            }
                        },
                        "semantics": {
                            "type": "object",
                            "description": "Semantic information about the parameter field.",
                            "title": "Semantics",
                            "properties": {
                                "minCardinality": {
                                    "type": "integer",
                                    "description": "Minimum number of instances of this parameter per job.",
                                    "title": "Min cardinality",
                                    "default": 0,
                                    "minimum": 0,
                                    "required": false
                                },
                                "maxCardinality": {
                                    "title": "Max cardinality",
                                    "type": "integer",
                                    "description": "Max number of instances of this parameter per job.",
                                    "default": -1,
                                    "minimum": -1,
                                    "required": false
                                },
                                "ontology": {
                                    "title": "Ontology",
                                    "type": "array",
                                    "description": "Array of ontology terms describing this parameter.",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "value": {
                            "type": "object",
                            "description": "Default value and validations for the parameter field.",
                            "title": "Value",
                            "properties": {
                                "default": {
                                    "type": ["number","string"],
                                    "description": "Description of this parameter.",
                                    "title": "Default value"
                                },
                                "type": {
                                    "type": "string",
                                    "description": "The content type of the parameter.",
                                    "enum": ["string", "number", "bool", "enumeration", "flag"],
                                    "title": "Parameter type",
                                },
                                "validator": {
                                    "type": "string",
                                    "description": "The regular expression used to validate this parameter value.",
                                    "title": "Validator regex"
                                },
                                "enum_values": {
                                    "type": "array",
                                    "description": "The possible values this parameter accepts. A JSON array of string values should be provided.",
                                    "title": "Enumerated values",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "required": {
                                    "type": "boolean",
                                    "description": "Is this parameter required? If visible is false, this must be true.",
                                    "title": "Required"
                                },
                                "visible": {
                                    "type": "boolean",
                                    "description": "Should this parameter be visible? If not, there must be a default and it will be required.",
                                    "title": "Visible"
                                },
                                "order": {
                                    "type": "integer",
                                    "description": "The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.",
                                    "title": "Order",
                                }
                            }
                        }
                    }
                }
            }
        },
        //"required": ["name", "version", "label", "executionSystem", "executionType", "deploymentSystem", "deploymentPath"]//, "inputs.id", "parameters.id", "parameters[].visible", "parameters[].required"]
    };


    $scope.form = [{
        "type": "wizard",
        "legend": "General Info",
        "tabs": [

    //        {
    //            "title": "Data Inputs",
    //            "items": [
    //                {
    //                    "type": "tabarray",
    //                    "items": [
    //                        {
    //                            "key": "inputs[]",
    //                            "legend": "Input {{idx}}"
    //                        }
    //                    ]
    //                }
    //            ]
    //        },
            {
                "title": "Basics",
                "items": [
                    {
                      "key": "name",
                      "readonly": true,
                      // ngModelOptions: {
                      //     updateOnDefault: true
                      // },
                      // validationMessage: {
                      //   'required': 'Missing required'
                      // },
                      // $validators: {
                      //   required: function(value) {
                      //     return value ? true : false;
                      //   }
                      // }
                    },
                    {
                      "key": "version",
                      "readonly": true
                      // ngModelOptions: {
                      //     updateOnDefault: true
                      // },
                      // validationMessage: {
                      //   'required': 'Missing required'
                      // },
                      // $validators: {
                      //   required: function(value) {
                      //     return value ? true : false;
                      //   }
                      // }
                    },
                    "label",
                    "shortDescription",
                    "longDescription",
                    {
                        key: 'tags',
                        // type: 'input',
                        placeholder: 'One or more tags', //default will translate placeholder.select
                        options: {
                            tagging: true,
                            taggingLabel: '(new)',
                            taggingTokens: 'SPACE|ENTER|,'
                        }
                    },
                    "helpURI",
                    {
                        key: 'ontology',
                        placeholder: 'Semantic terms', //default will translate placeholder.select
                    }
                ]
            },
            {
                "title": "Dependencies",
                "items": [
                    "deploymentPath",
                    {
                        "key": "deploymentSystem",
                        "placeholder": "storage.example.com",
                        "type": "select",
                        titleMap: [],
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        }
                    },
                    "templatePath",
                    "testPath",
                    {
                        key: 'modules',
                        startEmpty: true,
                        placeholder: 'Module command(s)', //default will translate placeholder.select
                        notitle: true,
                        options: {
                            tagging: '',
                            taggingLabel: '(new)',
                            taggingTokens: ',|ENTER|,'
                        },
                        ngModelOptions: {
                            updateOnDefault: true
                        }
                    }
                ]
            },
            {
                "title": "Environment",
                "items": [
                    {
                        key: "executionType",
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        }
                    },
                    {
                        "key": "executionSystem",
                        "placeholder": "compute.example.com",
                        "type": "select",
                        titleMap: [],
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        },
                        onChange: function (modelValue, form) {
                            SystemsController.getSystemDetails(modelValue).then(
                                function(response) {
                                    $scope.systems.execution[modelValue].queues = response.queues;
                                    $scope.form[0].tabs[2].items[2].titleMap = [
                                        { value: '', name: 'Select queue'}
                                    ];

                                    angular.forEach($scope.systems.execution[modelValue].queues, function (queue, key) {
                                        $scope.form[0].tabs[2].items[2].titleMap.push({
                                            value: queue.name,
                                            name: queue.name
                                        });
                                    });
                                },
                                function(result) {
                                    // console.log("Failed to fetch " + modelValue + " system queues");
                                });
                        }
                    },
                    {
                        "key": "defaultQueue",
                        "type": "select",
                        // ngModelOptions: { updateOn: 'click' },
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        titleMap: [],
                        onChange: function (modelValue, form) {

                        }
                    },
                    "defaultNodeCount",
                    "defaultMemoryPerNode",
                    "defaultProcessorsPerNode",
                    "defaultMaxRunTime",
                    {
                        key: "parallelism",
                        type: "select",
                        // ngModelOptions: { updateOn: 'click' }
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                    },
                    {
                        "key": "checkpointable",
                        type: "radiobuttons",
                        // ngModelOptions: { updateOn: 'click' },
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        style: {
                            selected: "btn-success",
                            unselected: "btn-default"
                        },
                        titleMap: [
                            {value: true, name: "True"},
                            {value: false, name: "False"}
                        ]
                    }
                ]
            },
            {
                "title": "Parameters",
                "items": [
                    {
                        "type": "tabarray",
                        "title": "{{value.id || ('Parameter ' + $index)}}",
                        tabType: "top",
                        key: "parameters",
                        //remove: "Delete",
                        style: {
                            remove: "btn-danger"
                        },
                        add: "Add parameter",
                        "items": [
                            {
                                key: "parameters[].id",
                                // ngModelOptions: { updateOn: 'blur' },
                                ngModelOptions: {
                                    updateOnDefault: true
                                },
                                ngModel: function(ngModel) {
                                    ngModel.$validators.myMail = function(value) {
                                        var exp = /[a-zA-Z0-9_]+/.exec(value);
                                        if (!exp) {
                                            return false;
                                        }
                                        return true;
                                    };
                                },
                                validationMessage: {
                                    'invalidCharacters': "Invalid parameter id. Parameters must be alphanumeric strings and may include underscores."
                                }
                            },
                            {
                                "key": "parameters[].details",
                                "type": "fieldset",
                                "title": "Details",
                                "description": "Descriptive details about this app parameter used in form generation.",
                                "items": [
                                    "parameters[].details.label",
                                    // "parameters[].details.description",
                                    {
                                        "key": "parameters[].details.showArgument",
                                        type: "radiobuttons",
                                        // ngModelOptions: { updateOn: 'click' },
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        style: {
                                            selected: "btn-success",
                                            unselected: "btn-default"
                                        },
                                        titleMap: [
                                            {value: true, name: "True"},
                                            {value: false, name: "False"}
                                        ]
                                    },
                                    {
                                        "key": "parameters[].details.argument",
                                        "condition": "model.parameters[arrayIndex].details.showArgument",
                                        "title": "Command line argument"
                                    },
                                    {
                                        "key": "parameters[].details.repeatArgument",
                                        "type": "radiobuttons",
                                        // ngModelOptions: { updateOn: 'click' },
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },

                                        "condition": "model.parameters[arrayIndex].details.showArgument",
                                        "style": {
                                            selected: "btn-success",
                                            unselected: "btn-default"
                                        },
                                        titleMap: [
                                            {value: true, name: "True"},
                                            {value: false, name: "False"}
                                        ]
                                    }
                                ]
                            },
                            {
                                "key": "parameters[].semantics",
                                type: "fieldset",
                                "title": "Semantics",
                                "description": "Semantic information about the parameter field.",
                                "items": [
                                    {
                                      "key": "parameters[].semantics.ontology",
                                      startEmpty: true,
                                    },
                                    {
                                        key: "parameters[].semantics.minCardinality",
                                        type: "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'minLessThanMax': 'Minimum number of values allowed by this parameter must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'gtzeroWhenRequired': 'Minimum number of values allowed by this parameter must be greater than zero when required.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                              if (typeof $scope.model.parameteres !== 'undefined'){
                                                if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                      value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                      return false;
                                                  }
                                                }
                                              }
                                              return true;
                                            },
                                            gtzeroWhenRequired: function (value) {
                                              if (typeof $scope.model.parameteres !== 'undefined'){
                                                if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                      value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                      return false;
                                                  }
                                                }
                                              }
                                              return true;
                                            }
                                        },
                                    },
                                    {
                                        key: "parameters[].semantics.maxCardinality",
                                        type: "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'maxGreaterThanMax': 'Maximum number of values allowed by this parameter must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'oneWhenBoolish': 'Maximum number of values is one when parameter is of type bool or flag.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                               if (typeof $scope.model.parameters !== 'undefined'){
                                                if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                      value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                      return false;
                                                  }
                                                }
                                              }
                                                return true;
                                            },
                                            oneWhenBoolish: function (value) {
                                              if (typeof $scope.model.parameters !== 'undefined'){
                                                if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && ($scope.model.parameters[arrayIndex].value.type == 'bool' ||
                                                    $scope.model.parameters[arrayIndex].value.type == 'flag') &&
                                                    $scope.model.parameters[arrayIndex].semantics.maxCardinality > 1) {
                                                    return false;
                                                  }
                                                }
                                              }
                                              return true;
                                            }
                                        }
                                    }
                                ]
                            },
                            {
                                key: "parameters[].value",
                                "type": "fieldset",
                                "title": "Values",
                                "description": "Default value and validations for the parameter field.",
                                "items": [
                                    {
                                        key: "parameters[].value.type",
                                        type: "select",

                                    },
                                    {
                                        key: "parameters[].value.default",
                                        // ngModelOptions: {
                                        //     updateOnDefault: true
                                        // },
                                        // validationMessage: {
                                        //     'enumValueRequired': 'Default value must be one of the enumerated values for this parameter.',
                                        //     'defaultRequiredWhenHidden': 'Default value is required when the parameter is hidden.',
                                        // },
                                        // $validators: {
                                        //     // enumValueRequired: function (value) {
                                        //     //     if (value && $scope.model.parameters[arrayIndex].value.type == 'enum') {
                                        //     //         return ($scope.model.parameters[arrayIndex].value.enum_values.indexOf(value) != -1)
                                        //     //     }
                                        //     //     return true
                                        //     // },
                                        //     enumValueRequired: function (value) {
                                        //       return value ? true : false;
                                        //     },
                                        //     //defaultRequiredWhenHidden: function(value) {
                                        //     //    if (($scope.model.parameters[arrayIndex].value.type == 'bool' ||
                                        //     //        $scope.model.parameters[arrayIndex].value.type == 'flag') || &&
                                        //     //        $scope.model.parameters[arrayIndex].semantics.maxCardinality > 1)
                                        //     //    {
                                        //     //        return false;
                                        //     //    }
                                        //     //    return true
                                        //     //}
                                        // }
                                    },
                                    {
                                        key: "parameters[].value.validator",
                                        condition: "[string,number].indexOf(model.parameters[arrayIndex].value.type) !== -1",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        // TO-DO: Fix. This is breaking myForm.$valid
                                        // validationMessage: {
                                        //     'validatorNotSupported': 'Validators are not needed for enumeration, boolean, or flag parameter types',
                                        // },
                                        // $validators: {
                                        //     enumValueRequired: function (value) {
                                        //         return (value && [string, number].indexOf($scope.model.parameters[arrayIndex].value.type) !== -1);
                                        //     },
                                        // }
                                    },
                                    {
                                        key: "parameters[].value.enum_values",
                                        condition: "model.parameters[arrayIndex].value.type === 'enum'",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'enumNotSupported': 'Enumerated values are only supported for parameters of type enum.',
                                        },
                                        $validators: {
                                            enumNotSupported: function (value) {
                                                return (value && $scope.model.parameters[arrayIndex].value.type === 'enum');
                                            },
                                        }
                                    },
                                    {
                                        "key": "parameters[].value.required",
                                        "type": "radiobuttons",
                                        condition: "model.parameters[arrayIndex].value.visible",
                                        "style": {
                                            selected: "btn-success",
                                            unselected: "btn-default"
                                        },
                                        titleMap: [
                                            {value: true, name: "Yes"},
                                            {value: false, name: "No"}
                                        ],
                                        onChange: function (modelValue, form) {
                                          if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                            if (modelValue && $scope.model.parameters[arrayIndex].semantics.minCardinality == 0) {
                                                $scope.model.parameters[arrayIndex].semantics.minCardinality = 1;
                                            } else if (!modelValue && $scope.model.parameters[arrayIndex].semantics.minCardinality > 0) {
                                                $scope.model.parameters[arrayIndex].semantics.minCardinality = 0;
                                            }
                                          }
                                        }
                                    },
                                    {
                                        "key": "parameters[].value.visible",
                                        "type": "radiobuttons",
                                        // ngModelOptions: { updateOn: 'click' },
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        "style": {
                                            selected: "btn-success",
                                            unselected: "btn-default"
                                        },
                                        titleMap: [
                                            {value: true, name: "Yes"},
                                            {value: false, name: "No"}
                                        ],
                                        onChange: function (modelValue, form) {
                                           if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                            if (!modelValue) {
                                                $scope.model.parameters[arrayIndex].value.required = true
                                            }
                                          }
                                        }
                                    },
                                    "order"
                                ]
                            }

                        ]
                    }
                ]
            },
    //        {
    //            "title": "Data Output Data",
    //            "items": [
    //                {
    //                    "type": "tabarray",
    //                    "items": [
    //                        {
    //                            "key": "outputs[]",
    //                            "legend": "Parameter: {{idx}}"
    //                        }
    //                    ]
    //                }
    //            ]
    //        },

        ]
    }];

    $scope.model = {
       "tags": [
           ""
       ],
       "ontology": [
           "xs:string"
       ],
       "modules": [
           "load tacc"
       ],
       "parameters": [
           {
               "id": "param1",
               "details": {
                   "label": "first param",
                   "description": "something to do first"
               }
           },
           {
               "id": "param2",
               "details": {
                   "label": "param label 2",
                   "description": "something to do second"
               }
           }
       ],
       "executionSystem": "compute.example.com",
       "defaultQueue": "default",
       "defaultNodeCount": 1,
       "defaultMemoryPerNode": 4,
       "defaultProcessorsPerNode": 1,
       "defaultMaxRunTime": "24:00:00",
       "parallelism": "SERIAL",
       "deploymentPath": "/scratch/apps/foo-1.0",
       "deploymentSystem": "storage.example.com",
       "templatePath": "wrapper.sh",
       "testPath": "test/test/sh",
       "name": "foo",
       "version": "1.0",
       "label": "foo app",
       "helpURI": "http://help.com",
       "shortDescription": "foo demo",
       "longDescription": "foo demo app"
   };

    $scope.prettyModel = '{}';

    $scope.systems = {
        execution: [],
        storage: []
    }

    $scope.defaultSystems = {
        execution: null,
        storage: null
    }

    $scope.fetchUserSystems = function(query) {
        SystemsController.listSystems(null, null).then(
            function(systems) {
                angular.forEach(systems, function (system, key) {
                    if (system.type === SystemTypeEnum.STORAGE.toString()) {
                        $scope.systems.storage[system.id] = system;
                        $scope.form[0].tabs[1].items[1].titleMap.push({ value: system.id, name: system.name });
                        if (system.default == true) {
                            $scope.defaultSystems.storage = system;
                        }
                    } else {
                        $scope.systems.execution[system.id] = system;
                        $scope.form[0].tabs[2].items[1].titleMap.push({ value: system.id, name: system.name });
                        if (system.default == true) {
                            $scope.defaultSystems.execution = system;
                        }
                    }
                });

                $timeout(function() {
                    WizardHandler.activateTab($scope, $scope.currentTabIndex);
                }, 0);
            },
            function(response) {
                App.alert({
                    type: 'danger',
                    message: "Error fetching execution systems."
                });
            }
        );
    };

    $scope.currentTabIndex = 0;
    $scope.codeview = false;

    $scope.init = function() {
        if ($stateParams.appId) {
            AppsController.getAppDetails($stateParams.appId).then(
                function (response) {
                    if (response.result.lastModified){
                      delete response.result.lastModified;
                    }
                    if (response.result.revision){
                      delete response.result.revision;
                    }
                    if (response.result.uuid){
                      delete response.result.uuid;
                    }
                    if (response.result.getContext){
                      delete response.result.getContext;
                    }
                    if (response.result._links){
                      delete response.result._links;
                    }
                    if (response.result.available){
                      delete response.result.available;
                    }
                    if (response.result.icon){
                      delete response.result.icon;
                    }
                    $scope.model = response.result;
                    // check if user can edit
                    AppsController.getAppPermission($stateParams.appId, $localStorage.activeProfile.username)
                      .then(
                        function(permissions){
                          if (!permissions.result.permission.write){
                            $scope.edit = false;
                            $scope.wizview = 'code';
                            App.alert(
                              {
                                type: 'danger',
                                message: 'Error: User does not have permission to edit app'
                              }
                            );
                          }
                        },
                        function(permissions){
                          $scope.edit = false;
                          $scope.wizview = 'code';
                          var message = '';
                          if (permissions.errorResponse.message) {
                            message = 'Error: Cannot edit app - ' + permissions.errorResponse.message
                          } else if (permissions.errorResponse.fault){
                            message = 'Error: Cannot edit app - ' + permissions.errorResponse.fault.message;
                          } else {
                            message = 'Error: Cannot edit app - ';
                          }
                          App.alert(
                            {
                              type: 'danger',
                              message: message
                            }
                          );
                        }
                      );
                },
                function (response) {
                  $scope.edit = false;
                  $scope.wizview = 'code';
                  var message = '';
                  if (response.errorResponse.message) {
                    message = 'Error: Could not retrieve app - ' + response.errorResponse.message
                  } else if (response.errorResponse.fault){
                    message = 'Error: Could not retrieve app - ' + response.errorResponse.fault.message;
                  } else {
                    message = 'Error: Could not retrieve app';
                  }
                  App.alert(
                    {
                      type: 'danger',
                      message: message
                    }
                  );
                });
        }
        // check if WizardHandler service has current model
        if (typeof WizardHandler.model !== 'undefined'){
          if (WizardHandler.model.id){
            delete WizardHandler.model.id;
          }
          $scope.model = WizardHandler.model;
          delete WizardHandler.model;
        }
        $scope.fetchUserSystems();
        WizardHandler.activateTab($scope, $scope.currentTabIndex);
    }


    $scope.init();

    $scope.useDefinition = function(){
      // Save model in service and re-direct to builder wizard
      $scope.model.name = '';
      $scope.model.version = '';

      // angular.copy($scope.model, WizardHandler.model);

      WizardHandler.model = $scope.model;

      $location.path('/apps/new');
    };

    $scope.submit = function () {
        $scope.$broadcast('schemaFormValidate');
        if ($scope.myForm.$valid) {
          AppsController.addApp(JSON.stringify($scope.model))
            .then(
              function(response){
                $uibModal.open({
                  templateUrl: "views/apps/submit-success.html",
                  scope: $scope,
                  size: 'lg',
                  controller: ['$scope', '$modalInstance', function($scope, $modalInstance ) {
                    $scope.close = function()
                    {
                        $modalInstance.dismiss('cancel');
                    };
                    $scope.browse = function(){
                        $location.path('/apps');
                    }
                  }]
                });
              },
              function(response){
                var message = '';
                if (response.errorResponse.message) {
                  message = 'Error: Could not create app - ' + response.errorResponse.message
                } else if (response.errorResponse.fault){
                  message = 'Error: Could not create app - ' + response.errorResponse.fault.message;
                } else {
                  message = 'Error: Could not create app';
                }
                App.alert(
                  {
                    type: 'danger',
                    message: message
                  }
                );
              }
            );
        } else {
          App.alert({
              type: 'danger',
              message: "There was an error creating your app: Form is not valid. Please verify all fields."
          });
        }
    };

    $scope.nextStep = function () {
        WizardHandler.validateTab($scope, $scope.currentTabIndex).then(function () {
            WizardHandler.activateTab($scope, ++$scope.currentTabIndex);
        });
    };

    $scope.previousStep = function () {
        WizardHandler.activateTab($scope, --$scope.currentTabIndex);
    };

    $scope.wizview = 'split';


    $scope.updateWizardLayout = function() {
        // console.log($scope.wizview);
    };


    $scope.codemirrorLoaded = function(_editor) {
        // Events
        _editor.on("change", function () {
            // if (_editor.hasFocus()) {
            //     $scope.model = JSON.parse(_editor.getValue());
            // }
            $timeout(function() {
                if (_editor.getValue() === ''){
                  $scope.model = '';
                } else {
                  try {
                    $scope.model = JSON.parse(_editor.getValue());
                  } catch(error) {
                    App.alert({
                        type: 'danger',
                        message: error
                    });
                  }

                }
            }, 0);
        });
        _editor.on("blur", function () {
            if (_editor.hasFocus()) {
                $scope.model = JSON.parse(_editor.getValue());
            }
        });
    };

    // CodeMirror editor support
    $scope.editorConfig = {
        lineWrapping : true,
        lineNumbers: true,
        matchBrackets: true,
        styleActiveLine: false,
        theme:'neat',
        mode: 'javascript',
        json: true,
        statementIndent: 2,
        onLoad: $scope.codemirrorLoaded
    };

    $scope.$watch('model', function(currentModel){
        if (currentModel === ''){
          $scope.model = {};
        }
        if (currentModel){
            $scope.prettyModel = JSON.stringify(currentModel, undefined, 2);
        }
    }, true);

    $scope.$watch('model.modules', function(newValue, oldValue){
        if (typeof newValue === 'undefined' && $scope.model !== ''){
          $scope.model.modules = [];
        }
        if (Object.prototype.toString.call( newValue ) === '[object Array]'){
          $scope.model.ontology = [];
        }
    }, true);
    //
    $scope.$watch('model.ontology', function(newValue, oldValue){
        if (typeof newValue === 'undefined' && typeof $scope.model !== 'undefined'){
          $scope.model.ontology = [];
        }
        if (Object.prototype.toString.call( newValue ) === '[object Array]'){
          $scope.model.ontology = [];
        }
    }, true);
    //
    $scope.$watch('model.parameters', function(newValue, oldValue){
        if (typeof newValue === 'undefined'){
          $scope.model.parameters = [];
        }
        if (Object.prototype.toString.call( newValue ) === '[object Array]'){
          $scope.model.ontology = [];
        }
    }, true);

    $scope.$watch('model.tags', function(newValue, oldValue){
        if (typeof newValue === 'undefined'){
          $scope.model.tags = [];
        }
        if (Object.prototype.toString.call( newValue ) === '[object Array]'){
          $scope.model.ontology = [];
        }
    }, true);


});
