angular.module('AgaveToGo').controller('AppEditWizardController', function ($injector, $timeout, $rootScope, $scope, $state, $location, $stateParams, $q, $uibModal, $localStorage, $location, $translate, Commons, AppsController, WizardHandler, SystemsController, SystemTypeEnum, Tags, FilesController, MessageService) {

    $scope.schema = {
        "type": "object",
        "title": "Interactive app registration form for the Agave platform.",
        "properties": {
            "name": {
                "type": "string",
                "description": "The name of the application. The name does not have to be unique, but the combination of name and version does.",
                "title": "Name",
                "validator": "[a-zA-Z_\\-\\.]+",
                "minLength": 3,
                "maxLength": 64
            },
            "version": {
                "type": "string",
                "description": "The version of the application in #.#.# format. While the version does not need to be unique, the combination of name and version does have to be unique.",
                "title": "Version",
                "validator": "\\d+(\\.\\d+)+",
                "minLength": 3,
                "maxLength": 16
            },
            "helpURI": {
                "type": "string",
                "description": "The URL where users can go for more information about the app.",
                "format": "url",
                "title": "Help URL",
                "validator": "(http|https)://[\\w-]+(\\.[\\w-]*)+([\\w.,@?^=%&amp;:/~+#-]*[\\w@?^=%&amp;/~+#-])?"
            },
            "label": {
                "type": "string",
                "description": "Label for use in forms generated by the jobs service",
                "title": "Label"
            },
            "icon": {
                "type": "string",
                "description": "The icon url to associate with this app.",
                "title": "Icon",
                "validator": "(http|https)://[\\w-]+(\\.[\\w-]*)+([\\w.,@?^=%&amp;:/~+#-]*[\\w@?^=%&amp;/~+#-])?"
            },
            "shortDescription": {
                "type": "string",
                "description": "Short description of this app",
                "maxLength": 128,
                "title": "Short description"
            },
            "longDescription": {
                "type": "string",
                "description": "Full description of this app",
                "maxLength": 32768,
                "title": "Long description"
            },
            "defaultQueue": {
                "type": [null,"string"],
                "description": "Default queue to use when submitting this job if none is provided in the job request. Can be left blank and a queue will be determined at run time.",
                "maxLength": 128,
                "title": "Default queue"
            },
            "defaultNodeCount": {
                "type": "integer",
                "description": "Default number of nodes to be used when running this app if no node count is given in the job request",
                "maxLength": 12,
                "minimum": 0,
                "exclusiveMinimum": true,
                "title": "Default node count",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 1
                }
            },
            "defaultMemoryPerNode": {
                "type": "number",
                "description": "Default memory in GB to be used when running this app if no memory is given in the job request",
                "maxLength": 9,
                "minimum": 0,
                "exclusiveMinimum": true,
                "title": "Default memory (GB)",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 4
                }
            },
            "defaultProcessorsPerNode": {
                "type": "integer",
                "description": "Default number of processors per node to be used when running this app if no processor count is given in the job request",
                "maxLength": 12,
                "title": "Default processor count",
                "x-schema-form": {
                    "type": "number",
                    "placeholder": 1
                }
            },
            "defaultMaxRunTime": {
                "type": "string",
                "description": "Default max run time to be used when running this app if no requested run time is given in the job request",
                "maxLength": 10,
                "title": "Default run time",
                "validator": "^(?:[0-9]{1,3}?[0-9]):[0-5][0-9]:[0-5][0-9]$",
                "x-schema-form": {
                    "type": "input",
                    "placeholder": "24:00:00"
                }
            },
            "ontology": {
                "type": "array",
                "description": "An array of ontology terms describing this app.",
                "items": {
                    "type": "string"
                },
                "title": "Ontology"
            },
            "executionSystem": {
                "type": "string",
                "description": "The ID of the execution system where this app should run.",
                "items": [],
                "title": "Execution system"
            },
            "executionType": {
                "type": "string",
                "description": "The execution type of the application. If you're unsure, it's probably HPC.",
                "enum": [
                    "CLI", "HPC", "CONDOR"
                ],
                "title": "Execution type"
            },
            "parallelism": {
                "type": "string",
                "description": "The parallelism type of the application. If you're unsure, it's probably SERIAL.",
                "enum": [
                    "SERIAL",
                    "PARALLEL",
                    "PTHREAD"
                ],
                "title": "Parallelism"
            },
            "deploymentPath": {
                "type": "string",
                "description": "The path to the folder on the deployment system containing the application wrapper and dependencies.",
                "title": "Deployment path"
            },
            "deploymentSystem": {
                "type": "string",
                "description": "The ID of the storage system where this app's assets should be stored.",
                "items": [],
                "title": "Deployment system"
            },
            "templatePath": {
                "type": "string",
                "description": "The path to the wrapper script relative to the deploymentPath.",
                "title": "Wrapper script"
            },
            "testPath": {
                "type": "string",
                "description": "The path to the test script relative to the deploymentPath.",
                "title": "Test script"
            },
            "checkpointable": {
                "type": "boolean",
                "description": "Does this app support checkpointing?",
                "title": "Checkpointable"
            },
            "tags": {
                "type": "array",
                "description": "Array of terms you may associate with this app",
                "items": {
                    "type": "string"
                },
                "title": "Tags"
            },
            "modules": {
                "type": "array",
                "description": "An array of modules to load prior to the execution of the application. This is only relevant when you use the unix Modules or LMOD utilities to manage dependencies on the app execution system.",
                "items": {
                    "type": "string",
                },
                // "required": [],
                "title": "Modules"
            },
            "inputs": {
                "type": "array",
                "description": "Inputs supported by this application.",
                "items": {
                    "type": "object",
                    "title": "Input",
                    "properties": {
                      "id": {
                        "type": "string",
                        "description": "The unique identifier for this input file. This will be referenced in the wrapper script.",
                        "required": true,
                        "title": "ID",
                        "valueInLegend": true
                      },
                      "details": {
                        "type": "object",
                        "description": "Descriptive details about this app input used in form generation.",
                        "title": "Details",
                        "properties": {
                            "argument": {
                                "type": "string",
                                "description": "Name of the command line flag or argument (including dashes) for this input.",
                                "title": "Argument value"
                            },
                            "description": {
                                "type": "string",
                                "description": "Verbose information on what this input does.",
                                "title": "Description"
                            },
                            "label": {
                                "type": "string",
                                "description": "The label displayed for this input.",
                                "title": "Label"
                            },
                            "showArgument": {
                                "type": "boolean",
                                "description": "Should this command line argument be injected into the submit script preceding the input?",
                                "title": "Prepend command line argument?",
                                "default": true
                            },
                            "repeatArgument": {
                                "type": "boolean",
                                "description": "In instances where multiple values are supplied for this input, should this command line argument be repeatedly injected into the submit script preceding every instance of the input value?",
                                "title": "Repeat argument for every value?",
                                "default": false
                            }
                        }
                      },
                        "semantics": {
                            "type": "object",
                            "description": "Semantic information about the input field.",
                            "title": "Semantics",
                            "properties": {
                                "fileTypes": {
                                     "type": "array",
                                     "description": "Array of file types required for this input.",
                                     "items": {
                                         "type": "string"
                                     },
                                     "title": "File types"
                                },
                                "minCardinality": {
                                    "type": "integer",
                                    "description": "Minimum number of instances of this input per job.",
                                    "title": "Min cardinality",
                                    "default": 0,
                                    "minimum": 0,
                                    "required": false
                                },
                                "maxCardinality": {
                                    "title": "Max cardinality",
                                    "type": "integer",
                                    "description": "Max number of instances of this input per job.",
                                    "default": -1,
                                    "minimum": -1,
                                    "required": false
                                },
                                "ontology": {
                                    "title": "Ontology",
                                    "type": "array",
                                    "description": "Array of ontology terms describing this input.",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "value": {
                            "type": "object",
                            "description": "Default value and validations for the parameter field.",
                            "title": "Value",
                            "properties": {
                                "default": {
                                    "type": ["number","string"],
                                    "description": "Default value",
                                    "title": "Default value"
                                },
                                "order": {
                                    "type": "integer",
                                    "description": "The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.",
                                    "title": "Order",
                                },
                                "validator": {
                                    "type": "string",
                                    "description": "The regular expression used to validate this parameter value.",
                                    "title": "Validator regex"
                                },
                                "required": {
                                    "type": "boolean",
                                    "description": "Is this parameter required? If visible is false, this must be true.",
                                    "title": "Required",
                                    "default": true
                                },
                                "visible": {
                                    "type": "boolean",
                                    "description": "Should this parameter be visible? If not, there must be a default and it will be required.",
                                    "title": "Visible",
                                    "default": true
                                },
                                "enquote": {
                                    "type": "boolean",
                                    "description": "Should this value be double quoted prior to injection in the wrapper template.",
                                    "title": "Visible",
                                    "default": true,
                                    "required": true
                                }
                            }
                        }
                    }
                }
            },
            "parameters": {
                "type": "array",
                "description": "Non-file inputs supported by this application.",
                "items": {
                    "type": "object",
                    "title": "Parameter",
                    "properties": {
                        "id": {
                            "type": "string",
                            "maxLength": 256,
                            "minLength": 1,
                            "description": "The unique identifier for this parameter. This will be referenced in the wrapper script.",
                            "title": "Parameter ID"
                        },
                        "details": {
                            "type": "object",
                            "description": "Descriptive details about this app parameter used in form generation.",
                            "title": "Details",
                            "properties": {
                                "label": {
                                    "type": "string",
                                    "description": "The label displayed for this parameter .",
                                    "title": "Label"
                                },
                                "description": {
                                    "type": "string",
                                    "description": "Verbose information on what this parameter does.",
                                    "title": "Description"
                                },
                                "showArgument": {
                                    "type": "boolean",
                                    "description": "Should this command line argument be injected into the submit script preceding the parameter?",
                                    "title": "Prepend command line argument?"
                                },
                                "argument": {
                                    "type": "string",
                                    "description": "Name of the command line flag or argument (including dashes) for this parameter.",
                                    "title": "Argument value"
                                },
                                "repeatArgument": {
                                    "type": "boolean",
                                    "description": "In instances where multiple values are supplied for this parameter, should this command line argument be repeatedly injected into the submit script preceding every instance of the parameter value?",
                                    "title": "Repeat argument for every value?",
                                    "default": false
                                }
                            }
                        },
                        "semantics": {
                            "type": "object",
                            "description": "Semantic information about the parameter field.",
                            "title": "Semantics",
                            "properties": {
                                "minCardinality": {
                                    "type": "integer",
                                    "description": "Minimum number of instances of this parameter per job.",
                                    "title": "Min cardinality",
                                    "default": 0,
                                    "minimum": 0,
                                    "required": false
                                },
                                "maxCardinality": {
                                    "title": "Max cardinality",
                                    "type": "integer",
                                    "description": "Max number of instances of this parameter per job.",
                                    "default": -1,
                                    "minimum": -1,
                                    "required": false
                                },
                                "ontology": {
                                    "title": "Ontology",
                                    "type": "array",
                                    "description": "Array of ontology terms describing this parameter.",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "value": {
                            "type": "object",
                            "description": "Default value and validations for the parameter field.",
                            "title": "Value",
                            "properties": {
                                "default": {
                                    "type": ["number","string"],
                                    "description": "Description of this parameter.",
                                    "title": "Default value"
                                },
                                "type": {
                                    "type": "string",
                                    "description": "The content type of the parameter.",
                                    "enum": ["string", "number", "bool", "enumeration", "flag"],
                                    "title": "Parameter type",
                                },
                                "validator": {
                                    "type": "string",
                                    "description": "The regular expression used to validate this parameter value.",
                                    "title": "Validator regex"
                                },
                                "enum_values": {
                                    "type": "array",
                                    "description": "The possible values this parameter accepts. A JSON array of string values should be provided.",
                                    "title": "Enumerated values",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "required": {
                                    "type": "boolean",
                                    "description": "Is this parameter required? If visible is false, this must be true.",
                                    "title": "Required"
                                },
                                "visible": {
                                    "type": "boolean",
                                    "description": "Should this parameter be visible? If not, there must be a default and it will be required.",
                                    "title": "Visible"
                                },
                                "order": {
                                    "type": "integer",
                                    "description": "The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.",
                                    "title": "Order",
                                }
                            }
                        }
                    }
                }
            }
        }
    };


    $scope.form = [{
        "type": "wizard",
        "legend": "General Info",
        "tabs": [
            {
                "title": "Basics",
                "items": [
                    {
                      "key": "name",
                      "readonly": true,
                    },
                    {
                      "key": "version",
                      "readonly": true
                    },
                    "label",
                    "shortDescription",
                    "longDescription",
                    {
                        "key": 'tags',
                        "placeholder": 'One or more tags', //default will translate placeholder.select
                        "options": {
                            "tagging": true,
                            "taggingLabel": "(new)",
                            "taggingTokens": "SPACE|ENTER|,"
                        }
                    },
                    "helpURI",
                    {
                        "key": 'ontology',
                        "placeholder": "Semantic terms" //default will translate placeholder.select
                    }
                ]
            },
            {
                "title": "Dependencies",
                "items": [
                    "deploymentPath",
                    {
                        "key": "deploymentSystem",
                        "placeholder": "storage.example.com",
                        "type": "select",
                        "titleMap": [],
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        }
                    },
                    "templatePath",
                    "testPath",
                    {
                        "key": "modules",
                        "startEmpty": true,
                        "placeholder": "Module command(s)", //default will translate placeholder.select
                        "notitle": true,
                        "options": {
                            "tagging": '',
                            "taggingLabel": "(new)",
                            "taggingTokens": ",|ENTER|,"
                        },
                        ngModelOptions: {
                            updateOnDefault: true
                        }
                    }
                ]
            },
            {
                "title": "Environment",
                "items": [
                    {
                        "key": "executionType",
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        }
                    },
                    {
                        "key": "executionSystem",
                        "placeholder": "compute.example.com",
                        "type": "select",
                        "titleMap": [],
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                        validationMessage: {
                          'required': 'Missing required'
                        },
                        $validators: {
                          required: function(value) {
                            return value ? true : false;
                          }
                        },
                        onChange: function (modelValue, form) {
                            SystemsController.getSystemDetails(modelValue).then(
                                function(response) {
                                    $scope.systems.execution[modelValue].queues = response.result.queues;
                                    $scope.form[0].tabs[2].items[2].titleMap = [
                                        { value: '', name: 'Select queue'}
                                    ];

                                    angular.forEach($scope.systems.execution[modelValue].queues, function (queue, key) {
                                        $scope.form[0].tabs[2].items[2].titleMap.push({
                                            value: queue.name,
                                            name: queue.name
                                        });
                                    });
                                },
                                function(result) {
                                    // console.log("Failed to fetch " + modelValue + " system queues");
                                });
                        }
                    },
                    {
                        "key": "defaultQueue",
                        "title": "Default queue",
                        "description": "Default queue to use when submitting this job if none is provided in the job request. Can be left blank and a queue will be determined at run time",
                        "type": "select",
                        "condition": "model.executionSystem !== ''",
                        "titleMap": [],
                        ngModelOptions: {
                            updateOnDefault: true
                        }
                    },
                    "defaultNodeCount",
                    "defaultMemoryPerNode",
                    "defaultProcessorsPerNode",
                    "defaultMaxRunTime",
                    {
                        "key": "parallelism",
                        "type": "select",
                        ngModelOptions: {
                            updateOnDefault: true
                        },
                    },
                    {
                        "key": "checkpointable",
                        "type": "radiobuttons",
                        "style": {
                            "selected": "btn-success",
                            "unselected": "btn-default"
                        },
                        "titleMap": [
                            {"value": true, "name": "True"},
                            {"value": false, "name": "False"}
                        ],
                        ngModelOptions: {
                            updateOnDefault: true
                        }
                    }
                ]
            },
            {
                "title": "Parameters",
                "items": [
                    {
                        "type": "tabarray",
                        "title": "{{value.id || ('Parameter ' + $index)}}",
                        "tabType": "top",
                        "key": "parameters",
                        "style": {
                            "remove": "btn-danger"
                        },
                        "add": "Add parameter",
                        "startEmpty": true,
                        "items": [
                            {
                                "key": "parameters[].id",
                                ngModelOptions: {
                                    updateOnDefault: true
                                },
                                ngModel: function(ngModel) {
                                    ngModel.$validators.myMail = function(value) {
                                        var exp = /[a-zA-Z0-9_]+/.exec(value);
                                        if (!exp) {
                                            return false;
                                        }
                                        return true;
                                    };
                                },
                                validationMessage: {
                                    'invalidCharacters': "Invalid parameter id. Parameters must be alphanumeric strings and may include underscores."
                                }
                            },
                            {
                                "key": "parameters[].details",
                                "type": "fieldset",
                                "title": "Details",
                                "description": "Descriptive details about this app parameter used in form generation.",
                                "items": [
                                    "parameters[].details.label",
                                    // "parameters[].details.description",
                                    {
                                        "key": "parameters[].details.showArgument",
                                        "type": "radiobuttons",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "True"},
                                            {"value": false, "name": "False"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    },
                                    {
                                        "key": "parameters[].details.argument",
                                        "condition": "model.parameters[arrayIndex].details.showArgument",
                                        "title": "Command line argument"
                                    },
                                    {
                                        "key": "parameters[].details.repeatArgument",
                                        "type": "radiobuttons",
                                        "condition": "model.parameters[arrayIndex].details.showArgument",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "True"},
                                            {"value": false, "name": "False"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    }
                                ]
                            },
                            {
                                "key": "parameters[].semantics",
                                "type": "fieldset",
                                "title": "Semantics",
                                "description": "Semantic information about the parameter field.",
                                "items": [
                                    {
                                      "key": "parameters[].semantics.ontology",
                                      "startEmpty": true,
                                    },
                                    {
                                        "key": "parameters[].semantics.minCardinality",
                                        "type": "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'minLessThanMax': 'Minimum number of values allowed by this parameter must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'gtzeroWhenRequired': 'Minimum number of values allowed by this parameter must be greater than zero when required.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                                if (typeof $scope.model.parameteres !== 'undefined'){
                                                  if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                              },
                                              gtzeroWhenRequired: function (value) {
                                                if (typeof $scope.model.parameteres !== 'undefined'){
                                                  if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                              }
                                        },
                                    },
                                    {
                                        "key": "parameters[].semantics.maxCardinality",
                                        "type": "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'maxGreaterThanMax': 'Maximum number of values allowed by this parameter must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'oneWhenBoolish': 'Maximum number of values is one when parameter is of type bool or flag.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                                if (typeof $scope.model.parameters !== 'undefined'){
                                                  if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.parameters[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.parameters[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                            },
                                            oneWhenBoolish: function (value) {
                                              if (typeof $scope.model.parameters !== 'undefined'){
                                                if ($scope.model.parameters.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && ($scope.model.parameters[arrayIndex].value.type == 'bool' ||
                                                      $scope.model.parameters[arrayIndex].value.type == 'flag') &&
                                                      $scope.model.parameters[arrayIndex].semantics.maxCardinality > 1) {
                                                      return false;
                                                  }
                                                }
                                              }
                                              return true;
                                            }
                                        }
                                    }
                                ]
                            },
                            {
                                "key": "parameters[].value",
                                "type": "fieldset",
                                "title": "Values",
                                "description": "Default value and validations for the parameter field.",
                                "items": [
                                    {
                                        "key": "parameters[].value.type",
                                        "type": "select"

                                    },
                                    {
                                        "key": "parameters[].value.default",
                                        "description": "Default value",
                                        "title": "Default value"
                                    },
                                    {
                                        "key": "parameters[].value.validator",
                                        "condition": "[string,number].indexOf(model.parameters[arrayIndex].value.type) !== -1",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    },
                                    {
                                        "key": "parameters[].value.enum_values",
                                        "condition": "model.parameters[arrayIndex].value.type === 'enum'",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'enumNotSupported': 'Enumerated values are only supported for parameters of type enum.',
                                        },
                                        $validators: {
                                            enumNotSupported: function (value) {
                                                return (value && $scope.model.parameters[arrayIndex].value.type === 'enum');
                                            },
                                        }
                                    },
                                    {
                                        "key": "parameters[].value.visible",
                                        "type": "radiobuttons",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "Yes"},
                                            {"value": false, "name": "No"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        onChange: function (modelValue, form) {
                                          if (typeof $scope.model.parameters !== 'undefined'){
                                            if ($scope.model.parameters.length > 0 && typeof form.key !== 'undefined'){
                                              if (!modelValue) {
                                                  $scope.model.parameters[form.key[1]].value.required = true
                                              }
                                            }
                                          }
                                        }
                                    },
                                    {
                                        "key": "parameters[].value.required",
                                        "type": "radiobuttons",
                                        "condition": "model.parameters[arrayIndex].value.visible",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "Yes"},
                                            {"value": false, "name": "No"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        onChange: function (modelValue, form) {
                                          if (typeof $scope.model.parameters !== 'undefined'){
                                            if ($scope.model.parameters.length > 0 && typeof form.key !== 'undefined'){
                                              if (modelValue && $scope.model.parameters[form.key[1]].semantics.minCardinality == 0) {
                                                  $scope.model.parameters[form.key[1]].semantics.minCardinality = 1;
                                              } else if (!modelValue && $scope.model.parameters[form.key[1]].semantics.minCardinality > 0) {
                                                  $scope.model.parameters[form.key[1]].semantics.minCardinality = 0;
                                              }
                                            }
                                          }
                                        }
                                    },
                                    {
                                      "key": "parameters[].value.order"
                                    }
                                ]
                            }

                        ]
                    }
                ]
            },
            {
                "title": "Inputs",
                "items": [
                    {
                        "type": "tabarray",
                        "title": "{{value.id || ('Input ' + $index)}}",
                        "tabType": "top",
                        "key": "inputs",
                        "style": {
                            "remove": "btn-danger"
                        },
                        "add": "Add input",
                        "startEmpty": true,
                        "items": [
                            {
                                "key": "inputs[].id",
                                ngModelOptions: {
                                    updateOnDefault: true
                                },
                                ngModel: function(ngModel) {
                                    ngModel.$validators.myMail = function(value) {
                                        var exp = /[a-zA-Z0-9_]+/.exec(value);
                                        if (!exp) {
                                            return false;
                                        }
                                        return true;
                                    };
                                },
                                validationMessage: {
                                    'invalidCharacters': "Invalid input id. Inputs must be alphanumeric strings and may include underscores."
                                }
                            },
                            {
                                "key": "inputs[].details",
                                "type": "fieldset",
                                "title": "Details",
                                "description": "Descriptive details about this app inputs used in form generation.",
                                "items": [
                                    {
                                      "key": "inputs[].details.label"
                                    },
                                    {
                                        "key": "inputs[].details.showArgument",
                                        "type": "radiobuttons",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "True"},
                                            {"value": false, "name": "False"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    },
                                    {
                                        "key": "inputs[].details.argument",
                                        "condition": "model.parameters[arrayIndex].details.showArgument",
                                        "title": "Command line argument"
                                    },
                                    {
                                        "key": "inputs[].details.repeatArgument",
                                        "type": "radiobuttons",
                                        "condition": "model.inputs[arrayIndex].details.showArgument",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "True"},
                                            {"value": false, "name": "False"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    }
                                ]
                            },
                            {
                                "key": "inputs[].semantics",
                                "type": "fieldset",
                                "title": "Semantics",
                                "description": "Semantic information about the input field.",
                                "items": [
                                    {
                                      "key": "inputs[].semantics.ontology",
                                      "startEmpty": true,
                                    },
                                    {
                                        "key": "inputs[].semantics.minCardinality",
                                        "type": "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'minLessThanMax': 'Minimum number of values allowed by this input must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'gtzeroWhenRequired': 'Minimum number of values allowed by this input must be greater than zero when required.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                                if (typeof $scope.model.inputs !== 'undefined'){
                                                  if ($scope.model.inputs.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.inputs[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.inputs[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                              },
                                              gtzeroWhenRequired: function (value) {
                                                if (typeof $scope.model.inputs !== 'undefined'){
                                                  if ($scope.model.inputs.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.inputs[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.inputs[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                              }
                                        },
                                    },
                                    {
                                        "key": "inputs[].semantics.maxCardinality",
                                        "type": "number",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        validationMessage: {
                                            'maxGreaterThanMax': 'Maximum number of values allowed by this parameter must be a non-negative integer value less than or equal to the maximum number of values.',
                                            'oneWhenBoolish': 'Maximum number of values is one when parameter is of type bool or flag.',
                                        },
                                        $validators: {
                                            minLessThanMax: function (value) {
                                                if (typeof $scope.model.inputs !== 'undefined'){
                                                  if ($scope.model.inputs.length > 0 && typeof arrayIndex !== 'undefined'){
                                                    if (value && $scope.model.inputs[arrayIndex].semantics.maxCardinality > 0 &&
                                                        value > $scope.model.inputs[arrayIndex].semantics.maxCardinality) {
                                                        return false;
                                                    }
                                                  }
                                                }
                                                return true;
                                            },
                                            oneWhenBoolish: function (value) {
                                              if (typeof $scope.model.inputs !== 'undefined'){
                                                if ($scope.model.inputs.length > 0 && typeof arrayIndex !== 'undefined'){
                                                  if (value && ($scope.model.inputs[arrayIndex].value.type == 'bool' ||
                                                      $scope.model.inputs[arrayIndex].value.type == 'flag') &&
                                                      $scope.model.inputs[arrayIndex].semantics.maxCardinality > 1) {
                                                      return false;
                                                  }
                                                }
                                              }
                                              return true;
                                            }
                                        }
                                    }
                                ]
                            },
                            {
                                "key": "inputs[].value",
                                "type": "fieldset",
                                "title": "Values",
                                "description": "Default value and validations for the input field.",
                                "items": [
                                    {
                                        "key": "inputs[].value.default",
                                        "description": "Default value",
                                        "title": "Default value"
                                    },
                                    {
                                        "key": "inputs[].value.validator",
                                        "condition": "[string,number].indexOf(model.inputs[arrayIndex].value.type) !== -1",
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        }
                                    },
                                    {
                                        "key": "inputs[].value.visible",
                                        "type": "radiobuttons",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "Yes"},
                                            {"value": false, "name": "No"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        onChange: function (modelValue, form) {
                                          if (typeof $scope.model.inputs !== 'undefined'){
                                            if ($scope.model.inputs.length > 0 && typeof form.key !== 'undefined'){
                                              if (!modelValue) {
                                                  $scope.model.inputs[form.key[1]].value.required = true
                                              }
                                            }
                                          }
                                        }
                                    },
                                    {
                                        "key": "inputs[].value.required",
                                        "type": "radiobuttons",
                                        "condition": "model.inputs[arrayIndex].value.visible",
                                        "style": {
                                            "selected": "btn-success",
                                            "unselected": "btn-default"
                                        },
                                        "titleMap": [
                                            {"value": true, "name": "Yes"},
                                            {"value": false, "name": "No"}
                                        ],
                                        ngModelOptions: {
                                            updateOnDefault: true
                                        },
                                        onChange: function (modelValue, form) {
                                          if (typeof $scope.model.inputs !== 'undefined'){
                                            if ($scope.model.inputs.length > 0 && typeof form.key !== 'undefined'){
                                              if (modelValue && $scope.model.inputs[form.key[1]].semantics.minCardinality == 0) {
                                                  $scope.model.inputs[form.key[1]].semantics.minCardinality = 1;
                                              } else if (!modelValue && $scope.model.parameters[form.key[1]].semantics.minCardinality > 0) {
                                                  $scope.model.inputs[form.key[1]].semantics.minCardinality = 0;
                                              }
                                            }
                                          }
                                        }
                                    },
                                    {
                                      "key": "inputs[].value.order"
                                    }
                                ]
                            }

                        ]
                    }
                ]
            }
        ]
    }];

    $scope.model = {
       "tags": [
           ""
       ],
       "ontology": [
           "xs:string"
       ],
       "modules": [
           "load tacc"
       ],
       "parameters": [
           {
               "id": "param1",
               "details": {
                   "label": "first param",
                   "description": "something to do first"
               }
           },
           {
               "id": "param2",
               "details": {
                   "label": "param label 2",
                   "description": "something to do second"
               }
           }
       ],
       "executionSystem": "compute.example.com",
       "defaultQueue": "default",
       "defaultNodeCount": 1,
       "defaultMemoryPerNode": 4,
       "defaultProcessorsPerNode": 1,
       "defaultMaxRunTime": "24:00:00",
       "parallelism": "SERIAL",
       "deploymentPath": "/scratch/apps/foo-1.0",
       "deploymentSystem": "storage.example.com",
       "templatePath": "wrapper.sh",
       "testPath": "test/test/sh",
       "name": "foo",
       "version": "1.0",
       "label": "foo app",
       "helpURI": "http://developer.agaveapi.co/",
       "shortDescription": "foo demo",
       "longDescription": "foo demo app"
   };

    $scope.prettyModel = '{}';

    $scope.systems = {
        execution: [],
        storage: []
    }

    $scope.defaultSystems = {
        execution: null,
        storage: null
    }

    $scope.fetchUserSystems = function(query) {
        SystemsController.listSystems(null, null).then(
            function(response) {
                angular.forEach(response.result, function (system, key) {
                    if (system.type === SystemTypeEnum.STORAGE.toString()) {
                        $scope.systems.storage[system.id] = system;
                        $scope.form[0].tabs[1].items[1].titleMap.push({ value: system.id, name: system.id });
                        if (system.default == true) {
                            $scope.defaultSystems.storage = system;
                        }
                    } else {
                        $scope.systems.execution[system.id] = system;
                        $scope.form[0].tabs[2].items[1].titleMap.push({ value: system.id, name: system.id });
                        if (system.default == true) {
                            $scope.defaultSystems.execution = system;
                        }
                    }
                });

                $timeout(function() {
                    WizardHandler.activateTab($scope, $scope.currentTabIndex);
                }, 0);
            },
            function(response) {
              MessageService.handle(response, $translate.instant('error_systems_list'));
            }
        );
    };

    $scope.currentTabIndex = 0;
    $scope.codeview = false;

    $scope.init = function() {
        if ($stateParams.appId) {
            AppsController.getAppDetails($stateParams.appId).then(
                function (response) {
                    if (response.result.lastModified){
                      delete response.result.lastModified;
                    }
                    if (response.result.revision){
                      delete response.result.revision;
                    }
                    if (response.result.uuid){
                      delete response.result.uuid;
                    }
                    if (response.result.getContext){
                      delete response.result.getContext;
                    }
                    if (response.result._links){
                      delete response.result._links;
                    }
                    if (response.result.available){
                      delete response.result.available;
                    }
                    if (response.result.icon){
                      delete response.result.icon;
                    }
                    $scope.model = response.result;
                    // check if user can edit
                    AppsController.getAppPermission($stateParams.appId, $localStorage.activeProfile.username)
                      .then(
                        function(permissions){
                          if (!permissions.result.permission.write){
                            $scope.edit = false;
                            $scope.wizview = 'code';
                            App.alert(
                              {
                                type: 'danger',
                                message: $translate.instant('error_apps_edit_permission')
                              }
                            );
                          }
                        },
                        function(permissions){
                          $scope.edit = false;
                          $scope.wizview = 'code';
                          MessageService.handle(response, $translate.instant('error_apps_edit_permission'));
                        }
                      );
                },
                function (response) {
                  $scope.edit = false;
                  $scope.wizview = 'code';
                  MessageService.handle(response, $translate.instant('error_apps_details'));
                });
        }
        // check if WizardHandler service has current model
        if (typeof WizardHandler.model !== 'undefined'){
          if (WizardHandler.model.id){
            delete WizardHandler.model.id;
          }
          $scope.model = WizardHandler.model;
          delete WizardHandler.model;
        }
        $scope.fetchUserSystems();
        WizardHandler.activateTab($scope, $scope.currentTabIndex);
    }


    $scope.init();

    $scope.useDefinition = function(){
      // Save model in service and re-direct to builder wizard
      $scope.model.name = '';
      $scope.model.version = '';

      // angular.copy($scope.model, WizardHandler.model);

      WizardHandler.model = $scope.model;

      $location.path('/apps/new');
    };

    $scope.submit = function () {
        $scope.$broadcast('schemaFormValidate');
        if ($scope.myForm.$valid) {
          AppsController.addApp(JSON.stringify($scope.model))
            .then(
              function(response){
                $uibModal.open({
                  templateUrl: "views/apps/submit-success.html",
                  scope: $scope,
                  size: 'lg',
                  controller: ['$scope', '$modalInstance', function($scope, $modalInstance ) {
                    $scope.close = function()
                    {
                        $modalInstance.dismiss('cancel');
                    };
                    $scope.browse = function(){
                        $location.path('/apps');
                    }
                  }]
                });
              },
              function(response){
                MessageService.handle(response, $translate.instant('error_apps_edit'));
              }
            );
        } else {
          App.alert({
              type: 'danger',
              message: $translate.instant('error_apps_form')
          });
        }
    };

    $scope.nextStep = function () {
        WizardHandler.validateTab($scope, $scope.currentTabIndex).then(function () {
            WizardHandler.activateTab($scope, ++$scope.currentTabIndex);
        });
    };

    $scope.previousStep = function () {
        WizardHandler.activateTab($scope, --$scope.currentTabIndex);
    };

    $scope.wizview = 'split';


    $scope.updateWizardLayout = function() {
        // console.log($scope.wizview);
    };


    $scope.codemirrorLoaded = function(_editor) {
        // Events
        _editor.on("change", function () {
            // if (_editor.hasFocus()) {
            //     $scope.model = JSON.parse(_editor.getValue());
            // }
            $timeout(function() {
                if (_editor.getValue() === ''){
                  $scope.model = '';
                } else {
                  try {
                    $scope.model = JSON.parse(_editor.getValue());
                  } catch(error) {
                    App.alert({
                        type: 'danger',
                        message: error
                    });
                  }

                }
            }, 0);
        });
        _editor.on("blur", function () {
            if (_editor.hasFocus()) {
                $scope.model = JSON.parse(_editor.getValue());
            }
        });
    };

    // CodeMirror editor support
    $scope.editorConfig = {
        lineWrapping : true,
        lineNumbers: true,
        matchBrackets: true,
        styleActiveLine: false,
        theme:"neat",
        mode: "javascript",
        json: true,
        statementIndent: 2,
        onLoad: $scope.codemirrorLoaded
    };

    $scope.$watch('model', function(currentModel){
        // if (currentModel === ''){
        //   $scope.model = {};
        // }
        if (currentModel){
            $scope.prettyModel = JSON.stringify(currentModel, undefined, 2);
        }
    }, true);

    $scope.$watch('model.modules', function(newValue, oldValue){
        if (typeof newValue === 'undefined' && $scope.model !== ''){
          $scope.model.modules = [];
        }
        // if (Object.prototype.toString.call( newValue ) === '[object Array]'){
        //   $scope.model.modules = [];
        // }
    }, true);

    $scope.$watch('model.ontology', function(newValue, oldValue){
        if (typeof newValue === 'undefined'){
          $scope.model.ontology = [];
        }
        // if (Object.prototype.toString.call( newValue ) === '[object Array]'){
        //   $scope.model.ontology = [];
        // }
    }, true);

    $scope.$watch('model.tags', function(newValue, oldValue){
        if (typeof newValue === 'undefined'){
          $scope.model.tags = [];
        }
        // if (Object.prototype.toString.call( newValue ) === '[object Array]'){
        //   $scope.model.tags = [];
        // }
    }, true);

    $scope.$watch('model.parameters', function(newValue, oldValue){
        if (typeof newValue === 'undefined'){
          $scope.model.parameters = [];
        }
        // if (Object.prototype.toString.call( newValue ) === '[object Array]'){
        //   $scope.model.parameters = [];
        // }
    }, true);


});
